# Generated by Django 5.1a1 on 2024-06-09 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0002_borrowing_borrow_date_not_past_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="borrow_date_not_past",
        ),
    ]
